### PR TITLE
chore: Run script to update all docs

### PR DESCRIPTION
**Pull request by RajatPawar**

### CODE REVIEW

**Comment by RajatPawar** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/amp-labs/docs/90?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#92** <a href="https://app.graphite.dev/github/pr/amp-labs/docs/92?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#91** <a href="https://app.graphite.dev/github/pr/amp-labs/docs/91?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#90** <a href="https://app.graphite.dev/github/pr/amp-labs/docs/90?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/amp-labs/docs/90?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#89** <a href="https://app.graphite.dev/github/pr/amp-labs/docs/89?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by jatinsandilya — APPROVED** [review]

**Comment by RajatPawar** [comment]
@laurenzlong I'm holding off on merging this because it'll make the `on-demand read`  & the `deliver results on request` routes public in the docs, let me know if to go ahead with it

**Comment by laurenzlong** [comment]
we're not ready to release the on-demand read routes yet, since I'd like to make some tweaks to the request format.

**Comment by RajatPawar** [comment]
Sounds good. I haven't edited `mint.json` directly, the previous PR contained the updated script which was waiting on a review, and this PR contained the mint.json regenerated using that updated script

**Pull request closed without merging**
